config/routes.rb
Rails.application.routes.draw do
  get "pages/profile"
  get "pages/shop"
  get "pages/about"
  get "pages/contact"
  namespace :admin do
    resources :orders
    resources :products do
      resources :stocks 
    end
    resources :products
    resources :categories
  end
devise_for :admins, controllers: {
  sessions: 'admins/sessions',
  registrations: 'admins/registrations',
  passwords: 'admins/passwords'
}


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end
  resources :categories, only: [:show]
  resources :products, only: [:show]

  get "admin" => "admin#index"
  get "cart" => "carts#show"
  post "checkout" => "checkouts#create"
  get "success" => "checkouts#success"
  get "cancel" => "checkouts#cancel"
  post "/webhooks/stripe" => "webhooks#stripe"
  
  get "shop", to: "pages#shop", as: :shop
  get "about", to: "pages#about", as: :about
  get "contact", to: "pages#contact", as: :contact

end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_products, dependent: :destroy
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  before_action :set_admin_order, only: %i[ show edit update destroy ]

  # GET /admin/orders or /admin/orders.json
  def index
    @not_fulfilled_pagy, @not_fulfilled_orders = pagy(Order.where(fulfilled: false).order(created_at: :asc))
    @fulfilled_pagy, @fulfilled_orders = pagy(Order.where(fulfilled: true).order(created_at: :asc), page_param: :page_fulfilled)
  end

  # GET /admin/orders/1 or /admin/orders/1.json
  def show
  end

  # GET /admin/orders/new
  def new
    @admin_order = Order.new
  end

  # GET /admin/orders/1/edit
  def edit
  end

  # POST /admin/orders or /admin/orders.json
  def create
    @admin_order = Order.new(admin_order_params)

    respond_to do |format|
      if @admin_order.save
        format.html { redirect_to admin_order_path(@admin_order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @admin_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/orders/1 or /admin/orders/1.json
  def update
    respond_to do |format|
      if @admin_order.update(admin_order_params)
        format.html { redirect_to admin_order_path(@admin_order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/orders/1 or /admin/orders/1.json
  def destroy
    @admin_order.destroy!

    respond_to do |format|
      format.html { redirect_to admin_orders_path, status: :see_other, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_order
      @admin_order = Order.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def admin_order_params
      params.require(:order).permit(:customer_email, :fulfilled, :total, :address )
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= form_with(model: [:admin, admin_order], class: "contents") do |form| %>
  <% if admin_order.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(admin_order.errors.count, "error") %> prohibited this admin_order from being saved:</h2>
      <ul class="list-disc ml-6">
        <% admin_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :customer_email %>
    <%= form.text_field :customer_email, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": admin_order.errors[:customer_email].none?, "border-red-400 focus:outline-red-600": admin_order.errors[:customer_email].any?}] %>
  </div>

  <div class="my-5">
    <label class="inline-flex items-center gap-2 cursor-pointer">
      <%= form.check_box :fulfilled, class: ["rounded border h-5 w-5", {"border-gray-400 focus:outline-blue-600": admin_order.errors[:fulfilled].none?, "border-red-400 focus:outline-red-600": admin_order.errors[:fulfilled].any?}] %>
      <span class="select-none"><%= form.label :fulfilled, nil, class: "mb-0" %></span>
    </label>
  </div>

  <div class="my-5">
    <%= form.label :total %>
    <%= form.number_field :total, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": admin_order.errors[:total].none?, "border-red-400 focus:outline-red-600": admin_order.errors[:total].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :address %>
    <%= form.text_field :address, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": admin_order.errors[:address].none?, "border-red-400 focus:outline-red-600": admin_order.errors[:address].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/orders/_order.html.erb
<div id="<%= dom_id order %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Customer email:</strong>
    <%= order.customer_email %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Fulfilled:</strong>
    <%= order.fulfilled? ? "Yes" : "No" %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Total:</strong>
    <%= number_to_currency(order.total) %> <!-- if you want currency formatting -->
  </div>
  <div>
    <strong class="block font-medium mb-1">Address:</strong>
    <%= order.address %>
  </div>
  
  <% if order.order_products.any? %>
    <div>
      <strong class="block font-medium mb-2">Products:</strong>
      <ul class="space-y-2 list-disc list-inside">
        <% order.order_products.each do |op| %>
          <li>
            <span class="font-semibold"><%= op.product.name %></span> — 
            Size: <%= op.size %>, 
            Quantity: <%= op.quantity %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/admin/orders/edit.html.erb
<div class="md:w-2/3 w-full mx-auto px-4">
  <h1 class="font-bold text-4xl mb-6">Editing order</h1>

  <%= render "form", admin_order: @admin_order %>

  <div class="flex flex-col sm:flex-row sm:space-x-3 mt-6 gap-3">
    <%= link_to "Show this order", admin_order_path(@admin_order),
        class: "w-full sm:w-auto text-center rounded-md px-4 py-3 bg-gray-100 hover:bg-gray-200 text-gray-800 font-medium transition" %>
        
    <%= link_to "Back to orders", admin_orders_path,
        class: "w-full sm:w-auto text-center rounded-md px-4 py-3 bg-gray-100 hover:bg-gray-200 text-gray-800 font-medium transition" %>
  </div>
</div>

app/views/admin/orders/index.html.erb
<% content_for :title, "Orders" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice">
      <%= notice %>
    </p>
  <% end %>

  <div class="flex justify-between items-center mb-6">
    <h1 class="font-bold text-4xl">Orders</h1>
    <%= link_to "New order", new_admin_order_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <h2 class="mt-8 mb-4 text-2xl font-semibold">Unfulfilled Orders</h2>
  <div class="flex flex-col w-full">
    <div class="overflow-x-auto sm:mx-0.5 lg:mx-0.5 p-2">
      <div class="py-2 inline-block min-w-full">
        <div class="overflow-x-auto">
          <table class="min-w-full overflow-x-scroll">
            <thead class="bg-white border-b">
              <tr>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">Order ID</th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">Customer Email</th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">Address</th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">Total</th>
              </tr>
            </thead>
            <tbody>
              <% @not_fulfilled_orders.each do |o| %>
                <tr class="bg-gray-50 border-b">
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 underline">
                    <%= link_to o.id, [:admin, o], class: 'underline' %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800">
                    <%= o.customer_email %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800">
                    <%= o.address %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-800">
                    <%= number_to_currency(o.total / 100.0) %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%== pagy_nav(@not_fulfilled_pagy) if @not_fulfilled_pagy.pages > 1 %>
        </div>
      </div>
    </div>
  </div>

  <h2 class="mt-12 mb-4 text-2xl font-semibold">Fulfilled Orders</h2>
  <div class="flex flex-col w-full">
    <div class="overflow-x-auto sm:mx-0.5 lg:mx-0.5 p-2">
      <div class="py-2 inline-block min-w-full">
        <div class="overflow-x-auto">
          <table class="min-w-full overflow-x-scroll">
            <thead class="bg-white border-b">
              <tr>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">Order ID</th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">Customer Email</th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">Address</th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">Total</th>
              </tr>
            </thead>
            <tbody>
              <% @fulfilled_orders.each do |o| %>
                <tr class="bg-gray-50 border-b">
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 underline">
                    <%= link_to o.id, [:admin, o], class: 'underline' %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800">
                    <%= o.customer_email %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800">
                    <%= o.address %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-800">
                    <%= number_to_currency(o.total / 100.0) %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%== pagy_nav(@fulfilled_pagy) if @fulfilled_pagy.pages > 1 %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/new.html.erb
<% content_for :title, "New order" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl mb-6">New order</h1>

  <%= render "form", admin_order: @admin_order %>

  <%= link_to "Back to orders", admin_orders_path, class: "w-full sm:w-auto text-center mt-6 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/admin/orders/show.html.erb
<% content_for :title, "Showing order" %>

<div class="md:w-2/3 w-full mx-auto px-4">
  <div class="bg-white p-6 rounded-lg shadow-md">

    <% if notice.present? %>
      <p id="notice" class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block">
        <%= notice %>
      </p>
    <% end %>

    <h1 class="font-bold text-4xl mb-6">Showing order</h1>

    <%= render @admin_order %>

    <div class="flex flex-col sm:flex-row gap-2 mt-6">
      <%= link_to "Edit this order", edit_admin_order_path(@admin_order),
        class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 font-medium transition" %>

      <%= link_to "Back to orders", admin_orders_path,
        class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 font-medium transition" %>

      <%= button_to "Destroy this order", admin_order_path(@admin_order), method: :delete,
        form_class: "w-full sm:w-auto",
        class: "rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer transition",
        data: { turbo_confirm: "Are you sure?" } %>
    </div>

  </div>
</div>